-------------------
-- CREATE ROLES ---
-------------------

CREATE ROLE user_audit NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOLOGIN;CREATE ROLE user_sales NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN;

CREATE ROLE user_support NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN;

CREATE ROLE super_audit NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOLOGIN;

CREATE ROLE super_sales NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOLOGIN;

CREATE ROLE super_support NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOLOGIN;

CREATE ROLE sys_admin NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOLOGIN;

CREATE ROLE guest NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOLOGIN;
