CREATE ROLE "angie" LOGIN PASSWORD '421989' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
GRANT user_supply TO angie;

CREATE ROLE "ann" LOGIN PASSWORD 'ann' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
GRANT user_supply TO ann;
