DROP ROLE IF EXISTS maricel;
CREATE ROLE "maricel" LOGIN PASSWORD 'maricel' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
GRANT user_sales TO maricel;

DROP ROLE IF EXISTS maribel;
CREATE ROLE "maribel" LOGIN PASSWORD 'maribel' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
GRANT user_stock TO maribel;

DROP ROLE IF EXISTS ronavie;
CREATE ROLE "ronavie" LOGIN PASSWORD 'ronavie' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
GRANT user_finance TO ronavie;